version: '3.5'
services:
    pgsql:
        image: postgres:15
        container_name: pgsql
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: maya
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - traefik-public
networks:
    traefik-public:
        external: true
volumes:
    pgdata:
        driver: local
