name: Build & Deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Laravel app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
     
          script: |
            cd ~/app/jacksparrow
            git fetch
            git pull
            docker-compose -f docker-compose-prd.yml build
      - name: Deploy Laravel app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
     
          script: |
            cd ~/app/jacksparrow
            docker-compose -f docker-compose-prd.yml down
            docker-compose -f docker-compose-prd.yml up -d
  
