name: Build & Deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests
        run: php artisan test
      - name: Build Laravel app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd ~/app/jacksparrow
            git fetch
            git pull
            docker system prune -a --force
            docker-compose -f docker-compose-prd.yml build
            docker-compose -f docker-compose-prd.yml run --rm composer install
            docker-compose -f docker-compose-prd.yml run --rm node npm install
            docker-compose -f docker-compose-prd.yml run --rm api-app php artisan clear-compiled
            docker-compose -f docker-compose-prd.yml run --rm node npm run prod
      - name: Deploy Laravel app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd ~/app/jacksparrow
            docker service rm backend-api-app backend-api-scheduler backend-api-queue backend-api-redis backend-nginx
            docker stack deploy -c docker-compose-prd.yml backend

